import type { GateBPublicEvidence } from "../gateb/publicEvidence";
import type { Locale } from "../i18n/locale";

/**
 * English overlay for the published evidence artifact.
 *
 * `public/validation/gate-b-public.json` is generated by
 * `research/export_public_evidence.py` from the canonical summary, and it is
 * written in Indonesian. Translating it in place would fork a research
 * artifact, and every regeneration would silently revert the fork. So the
 * artifact stays the single source of the numbers, and this module supplies an
 * English reading of its prose, keyed by the stable ids the artifact already
 * carries.
 *
 * Anything not covered here falls through to the Indonesian original. An
 * untranslated sentence showing in Indonesian is a visible gap someone can
 * fix; a blank one is a bug that looks like a design.
 */

const EN_HEADLINE_TITLE = "The instrument responds to a deliberately produced pattern";

const EN_BOUNDARY =
  "Instrument responsivity in adults producing a pattern deliberately. Not sensitivity, not "
  + "specificity, not accuracy, and not a statement of any kind about autism.";

const EN_SATURATION_NOTE =
  "The AOI box is 28% of the screen wide while the median between-stream error is only 4.1% of "
  + "screen width. A number this high can hardly fail to occur, so it is not evidence of accuracy.";

const EN_ICC_CAVEAT =
  "ICC is a variance ratio. When every participant watches the same stimulus, between-participant "
  + "variance is small, so ICC can be low even when the absolute difference is small. That is why "
  + "the Bland-Altman limits of agreement are the primary metric, and ICC is reported as it stands.";

const EN_CAPABILITY: Record<string, { capability: string; statusLabel: string; boundary: string }> = {
  on_device_measurement_chain: {
    capability: "On-device measurement chain",
    statusLabel: "Ready for an engineering demonstration",
    boundary: "Gate A/B test technical measurement, not clinical screening.",
  },
  adult_responsivity: {
    capability: "Instrument response to a produced pattern",
    statusLabel: "Demonstrated on the adult positive control",
    boundary:
      "A manipulation check — not sensitivity, specificity, ASD, or any participant's clinical status.",
  },
  automatic_toddler_referral: {
    capability: "Automatic toddler referral",
    statusLabel: "Withheld",
    boundary:
      "The 69% comparison may only be demonstrated in demo mode, and issues no referral.",
  },
  operator_flow: {
    capability: "End-to-end operator flow",
    statusLabel: "Run repeatedly on real devices",
    boundary:
      "The operators were the project team, not Posyandu kader, and the location was not a Posyandu. This shows the flow can be run repeatedly on real devices and in real light; it does not show that kader can run it.",
  },
  kader_usability: {
    capability: "Usability by kader",
    statusLabel: "Not yet tested",
    boundary:
      "Requires testing of tasks, timing, failures, training, and support within a real service flow.",
  },
  indonesian_toddler_validity: {
    capability: "Validity in Indonesian toddlers",
    statusLabel: "Not yet tested",
    boundary:
      "Requires a partner able to run ethics review, informed parental consent, a blinded clinical reference, private linkage, recruitment, fairness and failure analysis, and prospective validation.",
  },
};

const EN_LIMITATIONS = [
  "The 2.36° error was measured in adults. There are no toddlers in this evidence.",
  "Gate B tests measurement agreement against WebGazer.js — not sensitivity, specificity, or ASD diagnostic accuracy.",
  "Absolute accuracy may only be quoted from the Gate A known-target block, never from between-stream agreement.",
  "The mean 13-feature ICC(A,1) is reported descriptively and is not a Gate B pass criterion.",
  "Clinical generalisation to toddlers still requires a prospective Gate C with independent clinical outcomes.",
];

const EN_FEATURE_READING: Record<string, string> = {
  ink_frac:
    "An ICC of 0.084 sounds bad, but the two streams never differed by more than 0.012 on a 0–1 scale.",
  radial_std: "The opposite case: high ICC and narrow limits of agreement, the two agree.",
  aspect_ratio:
    "The feature with the widest difference; reported so the limit is visible rather than hidden.",
};

const EN_STUDY = {
  title: "Neurogaze Gate B agreement test against WebGazer",
  population: "30 web app test sessions",
  acquisitionMode: "simultaneous_browser_streams",
};

const EN_TODDLER = {
  claim:
    "WebGazer is a ManyBabies-validated method for toddlers aged 18–27 months, which is why it is used as the Gate B comparator.",
  attritionNote:
    "The same study reports 42% attrition on toddler webcam sessions. That is the basis for NeuroGaze withholding a result rather than forcing a number.",
};

export type EvidenceCopy = {
  headlineTitle: string;
  boundary: string;
  saturationNote: string;
  iccCaveat: string;
  limitations: readonly string[];
  studyTitle: string;
  studyPopulation: string;
  acquisitionMode: string;
  toddlerClaim: string;
  toddlerAttritionNote: string;
  capability: (id: string) => { capability: string; statusLabel: string; boundary: string };
  featureReading: (feature: string) => string;
};

export function evidenceCopy(evidence: GateBPublicEvidence, locale: Locale): EvidenceCopy {
  const capabilities = evidence.readiness.capabilities;
  const examples = evidence.featureAgreement.examples;

  if (locale === "id") {
    return {
      headlineTitle: evidence.headline.title,
      boundary: evidence.positiveControl.boundary,
      saturationNote: evidence.agreement.saturationNote,
      iccCaveat: evidence.featureAgreement.iccCaveat,
      limitations: evidence.limitations,
      studyTitle: evidence.study.title,
      studyPopulation: evidence.study.population,
      acquisitionMode: evidence.study.acquisitionMode,
      toddlerClaim: evidence.toddlerReference.claim,
      toddlerAttritionNote: evidence.toddlerReference.attritionNote,
      capability: (id) => {
        const found = capabilities.find((item) => item.id === id);
        return {
          capability: found?.capability ?? id,
          statusLabel: found?.statusLabel ?? "",
          boundary: found?.boundary ?? "",
        };
      },
      featureReading: (feature) =>
        examples.find((item) => item.feature === feature)?.reading ?? "",
    };
  }

  return {
    headlineTitle: EN_HEADLINE_TITLE,
    boundary: EN_BOUNDARY,
    saturationNote: EN_SATURATION_NOTE,
    iccCaveat: EN_ICC_CAVEAT,
    // Length-matched to the artifact so a regenerated file that adds a
    // limitation still shows it, in Indonesian, rather than dropping it.
    limitations: evidence.limitations.map((original, index) => EN_LIMITATIONS[index] ?? original),
    studyTitle: EN_STUDY.title,
    studyPopulation: EN_STUDY.population,
    acquisitionMode: EN_STUDY.acquisitionMode,
    toddlerClaim: EN_TODDLER.claim,
    toddlerAttritionNote: EN_TODDLER.attritionNote,
    capability: (id) => {
      const found = capabilities.find((item) => item.id === id);
      const translated = EN_CAPABILITY[id];
      return {
        capability: translated?.capability ?? found?.capability ?? id,
        statusLabel: translated?.statusLabel ?? found?.statusLabel ?? "",
        boundary: translated?.boundary ?? found?.boundary ?? "",
      };
    },
    featureReading: (feature) =>
      EN_FEATURE_READING[feature]
      ?? examples.find((item) => item.feature === feature)?.reading
      ?? "",
  };
}
